### ISSUE TITLE
up repository!

### ISSUE THREAD

**Issue by TOWUK** [BGMP/CommandFramework#2]
https://maven.bgmp.cl/
![image](https://user-images.githubusercontent.com/28830162/127782977-69abab3c-3681-4486-88d8-6cf414a008e0.png)
 okay?

**Comment by BGMP** [comment]
I'm unable to replicate this issue. Everything is set up correctly on DeluxeHub's end, and the compiled binary required from maven is indeed up at my repo. Could you describe in detail the steps you followed to find yourself getting this error?

**Comment by TOWUK** [comment]
> I'm unable to replicate this issue. Everything is set up correctly on DeluxeHub's end, and the compiled binary required from maven is indeed up at my repo. Could you describe in detail the steps you followed to find yourself getting this error?

i clone repo and run **maven install**

**Comment by TOWUK** [comment]
![image](https://user-images.githubusercontent.com/28830162/127886775-a6893cfd-24fd-40f6-ba1c-0dbb18cbcd61.png)
web

**Comment by TOWUK** [comment]
its my provider idiots (russia rostelecom) sorry, close it issue!

**Comment by TOWUK** [comment]
use vpn
![image](https://user-images.githubusercontent.com/28830162/127887251-48f45011-ab57-43ff-a2f2-442918f709de.png)
