### ISSUE TITLE
Issues with using Maven 

### ISSUE THREAD

**Issue by benrobson** [BGMP/CommandFramework#3]
Hello,
I am attempting to use the CommandFramework and to `mvn install` onto a Maven project but https://maven.pkg.github.com/BGMP/CommandFramework is returning 404 and will not import.
Additionally I also followed https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-apache-maven-registry#installing-a-package with no luck.

**Comment by BGMP** [comment]
Hi there!

I'll give this a look when I'm back home in a couple of hours.

Thanks for your patience and for reporting this problem!

**Comment by BGMP** [comment]
Hey there again, @benrobson !

Hm... maybe you haven't authenticated through your `settings.xml`? According to [Authenticating to GitHub Packages](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-apache-maven-registry#authenticating-to-github-packages), you have to generate a token to read packages off of GitHub Packages and add a couple of modules to that file too.

This is quite inconvenient though... maybe migrating to these was a mistake 😅 . Depending on my sponsorships, I might be able to set up a Maven repository for `bgm.cl` again, like it used to be with `maven.bgm.cl`. Good times!

**Comment by benrobson** [comment]
Thankyou!
